{% set name = "prefect-aws" %}
{% set version = "0.4.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prefect_aws-{{ version }}.tar.gz
  sha256: e0c009a8945b0ecf46b6a28ba4965e2898c99eb2cb3aba15282c9780c6f3ee5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - boto3 >=1.24.53
    - botocore >=1.27.53
    - mypy-boto3-s3 >=1.24.94
    - mypy-boto3-secretsmanager >=1.26.49
    - prefect >=2.16.4
    - pyparsing >=3.1.1
    - tenacity >=8.0.0

test:
  imports:
    - prefect_aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PrefectHQ/prefect-aws
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Prefect collection of tasks and subflows to integrate with AWS
  doc_url: https://prefecthq.github.io/prefect-aws/
  dev_url: https://github.com/PrefectHQ/prefect-aws
  

extra:
  recipe-maintainers:
    - skrsna
    - ahuang11
    - desertaxle
